### ISSUE TITLE
PlantUML plugin PNG format doesn't work

### ISSUE THREAD

**Issue by haiyanghaiyang** [dkd/plantuml#13] opened 2017-10-16 13:11 UTC
I'm using Redmine 3.4.2, and the latest PlantUML plugin. The PlantUML plugin supports both png and svg format.

However, the png format doesn't work. It shows hex string only. I checked background Redmine log, which shows the generated png file is 0 byte. The svg format works fine.

Finally I got it working by workaround and here is the details, with PlantUML plugin tag v0.5.1.
1. This script works for svg, but not for png.
Bob -> Alice : hello
2. If I removed space between "Alice" and ":", as well as that between ":" and "hello", png works. This makes me thought svg works but png doesn't work. It looks png needs more strict requirement which should not have space in some specific position. I'm not sure anything wrong on my platform to have such issue.
Bob -> Alice:hello
3. In plantuml setting, no matter what binary I set, it always works. But if I leave it empty, the plugin doesn't work. I think it checks the binary location, but never use it.
4. This also works, if no space in "Bob->Alice", while keep spaces in "Alice : hello"
{{plantuml(png)
Bob->Alice : hello
}}

See discussion here,
http://www.redmine.org/boards/2/topics/53840

**Comment by ncreuschling** [comment] 2017-10-18 09:26
This is a duplicate of #11.

**Closed as completed by ncreuschling** 2017-10-18 09:26 UTC
Labels: duplicate
